FROM debian:stable

RUN apt update && \
    apt install -y \
        build-essential \
        golang \
        nodejs \
        openjdk-11-jdk \
        python3 \
        python3-pip \
    && apt-get clean
